name: Flutter Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Cache Flutter dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - uses: actions/setup-java@v4.2.2
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4.4.0
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Get App Info and Generate Message
        id: app_info
        run: |
          APP_NAME=$(grep -m 1 'name:' pubspec.yaml | awk '{print $2}' | tr -d "'")
          VERSION=$(grep -m 1 'version:' pubspec.yaml | awk '{print $2}' | tr -d "'")
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          echo "MESSAGE=New release: $APP_NAME v$VERSION%0A%0ALatest commit: $COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Send APK and Info to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="${{ steps.app_info.outputs.MESSAGE }}"

          curl -F document=@"build/app/outputs/flutter-apk/app-release.apk" \
          -F caption="$MESSAGE" \
          "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${TELEGRAM_CHAT_ID}"
