name: Flutter Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Cache Flutter dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - uses: actions/setup-java@v4.2.2
        with:
          distribution: "zulu"
          java-version: "21"

      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Cache Gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload APK
        uses: actions/upload-artifact@v4.4.0
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F document=@"build/app/outputs/flutter-apk/app-release.apk" \
          https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${TELEGRAM_CHAT_ID}
